[package]
name = "apexcharts-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.64"
