[package]
name = "apexcharts-rs"
description = "Rust WASM bindings for ApexCharts"
authors = ["Clement Wanjau <clementwanjau@gmail.com>"]
repository = "https://github.com/clementwanjau/apexcharts-rs"
version = "0.1.2"
edition = "2021"
license-file = "LICENSE"
keywords = ["apexcharts", "wasm", "rust", "web"]
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.64"
