[package]
name = "yew-chart"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["console"]}
console = "0.15.8"
yew = { version="0.21.0", features = ["csr"] }
apexcharts-rs = {path = "../../../apexcharts-rs", features = ["yew"]}
