name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Cargo Hack
        uses: taiki-e/install-action@cargo-hack
      - name: Build
        run: cargo hack build --target wasm32-unknown-unknown --lib --tests --examples --feature-powerset --mutually-exclusive-features yew,leptos
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
